# Site settings
title: "FRIENDRED"
description: >
  Blog | Materials | Wearable | Interactive performance 

author: FRIENDRED
email: friendred0@gmail.com
twitter_username:
github_username:

baseurl: "/friendred_blog" # the subpath of your site, e.g. /blog
url: "https://friendred.github.io/" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title

sass:
    style: compressed

exclude: [vendor]
